spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

logging:
  level:
    com.spacefurni: DEBUG
    org.hibernate.SQL: DEBUG
